apiVersion: v1
kind: Service
metadata:
  name: backend-erick-flores-service
  namespace: erick-flores-namespace
spec:
  type: NodePort 
  ports:
  - port: 30001
    targetPort: 8085  # Puerto donde escucha tu contenedor backend
    nodePort: 30001   # Puerto asignado en el nodo, opcional
  selector:
    app: backend-erick-flores-deployment