apiVersion: v1
kind: Service
metadata:
  name: frontend-erick-flores-service
  namespace: erick-flores-namespace
spec:
  type: NodePort 
  ports:
  - port: 30002
    targetPort: 4200 
    nodePort: 30002
  selector:
    app: frontend-erick-flores-deployment